# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('caddr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bankname', models.CharField(max_length=200)),
                ('cardno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('paymentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Phonecus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=15)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Phoneprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prname', models.CharField(max_length=500)),
                ('praddr', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamt', models.FloatField()),
                ('cartno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('prid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Producer')),
                ('receiptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Receipt')),
            ],
        ),
        migrations.AddField(
            model_name='phoneprod',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Producer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiptno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Receipt'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='buys',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='buys',
            name='receiptno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Receipt'),
        ),
    ]
